### ISSUE TITLE
Incorrect abbreviated plural for 'minutes', should be just 'min'

### ISSUE THREAD

**Issue by andreyz** [mattt/FormatterKit#159]
According to [General Rules for International System of Units (SI)](http://en.wikipedia.org/wiki/International_System_of_Units#General_rules):
> Symbols of units do not have a plural form; e.g., 25 kg, not 25 kgs.

Hence, instead of 'mins", localisation for English should be 'min'.

**Comment by mattt** [comment]
Sure. Please submit a PR with this change.
