### ISSUE TITLE
Duplicated resources when installing with Cocoapods 0.36

### ISSUE THREAD

**Issue by valeriomazzeo** [mattt/FormatterKit#161]
I honestly don't know if this is a problem of `Cocoapods` or `FormatterKit, but all the various resources get copied more than once as you can see in the screenshot:

![screen shot 2015-03-19 at 09 32 39](https://cloud.githubusercontent.com/assets/1882080/6727603/1d3d1296-ce1b-11e4-8daa-0aef30ea12c1.png)

This is really annoying because it generates loads of warnings.
Also is not happening on other pods, so it may be something related to the way `FormatterKit` is configured on the podspec.

**Comment by valeriomazzeo** [comment]
fix would be to not repeat to include the resources in every sub spec:

https://github.com/CocoaPods/CocoaPods/issues/3295

**Comment by fousa** [comment]
I have the same problem when adding the use_frameworks! line to my Podfile.

The fix above worked perfectly for me.

**Comment by grgcombs** [comment]
Ditto -- I effectively have to hand massage the FormatterKit target in order to build with an up-to-date cocoapods install.
