### ISSUE TITLE
weekOfYear = -2, ignored

### ISSUE THREAD

**Issue by orenmeiri** [mattt/FormatterKit#168]
stringForTimeInterval:-1354956 should return '2 weeks ago' but instead returns 1 day ago.
Looking at the code, it skips WeekOfYear because this line evaluates to 0

        if ((self.significantUnits & unit) && NSCalendarUnitCompareSignificance(self.leastSignificantUnit, unit) != NSOrderedDescending) {

because self.leastSignificantUnit is set by default to TTTCalendarUnitSecond which in enumerated lower value than TTTCalendarUnitWeek.

why is it necessary to check against leastSignificantUnit when we have bitmask with ALL significantUnits (self.significantUnites)?

**Comment by raybradley** [comment]
Had the same problem here. I believe this duplicates #162 which has a PR that fixes it.

**Comment by yas375** [comment]
Fixed by #162.
