### ISSUE TITLE
TTTTimeIntervalFormatter completely broken when weeks are involved.

### ISSUE THREAD

**Issue by moesalih** [mattt/FormatterKit#181]
1000000 seconds is around 11 days.

`[timeIntervalFormatter stringForTimeInterval:1000000]` return "4 days" instead of "1 week". The reason is that `NSCalendarUnitCompareSignificance` returns incorrect result when comparing weeks to other units, which will cause the week unit to be ignored.

How has this not been discovered yet?

**Comment by mathmatomancer** [comment]
I just stumbled across this as well, is a fix in progress?

**Comment by mathmatomancer** [comment]
I see some forks of this repository noticed that too, and just swapped the order. I used this one's fix in my project and it worked:
crazytonyli/FormatterKit/@dd286ee74489f9eae9216d6c37629b75d66727e7

**Comment by sebastianludwig** [comment]
Wich is PR #162

**Comment by yas375** [comment]
Fixed by #162.
