### ISSUE TITLE
Dependency warning when building with CocoaPods and use_frameworks!

### ISSUE THREAD

**Issue by MihaiDamian** [mattt/FormatterKit#182]
I have a podfile that looks like this:

    platform :ios, '8.0'
    
    use_frameworks!
    
    pod 'FormatterKit', '~> 1.8'

Building this produces a few hundred warnings of this type:

    Warning: Multiple build commands for output file /Users/mihai.damian/Desktop/Test2/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/ca.lproj
    Warning: Multiple build commands for output file /Users/mihai.damian/Desktop/Test2/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/ca.lproj
    Warning: Multiple build commands for output file /Users/mihai.damian/Desktop/Test2/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/ca.lproj
    Warning: Multiple build commands for output file /Users/mihai.damian/Desktop/Test2/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/ca.lproj
    Warning: Multiple build commands for output file /Users/mihai.damian/Desktop/Test2/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/ca.lproj
    Warning: Multiple build commands for output file /Users/mihai.damian/Desktop/Test2/Build/Products/Debug-iphonesimulator/Pods/FormatterKit.framework/ca.lproj

**Comment by ageorgios** [comment]
same issue here

**Comment by deada92** [comment]
here 2, any news about that?

**Comment by Ewg777** [comment]
+1

**Comment by yas375** [comment]
I suppose this has been fixed. Please try `1.8.1`.
