### ISSUE TITLE
Question regarding the usage of TTTTimeIntervalFormatter

### ISSUE THREAD

**Issue by oferRounds** [mattt/FormatterKit#194]
I would like present time as Facebook does, in its feed. That is:
- if it's today - x hours ago (or y minutes ago)
- if it's yesterday - Yesterday, at x:yz
- if it's > yesterday - Month day year, at x:yz

Is that possible?

Thanks a lot for your great library!

**Comment by yas375** [comment]
With `TTTTimeIntervalFormatter` you can get `5 minutes ago`, `yesterday` and so on. If you need something like `yesterday, at 8:25` you will probably need to combine result of `TTTTimeIntervalFormatter` with result of `NSDateFormatter` (without date style, only for time formatting).

**Comment by RishabhTayal** [comment]
On the other hand, if I want to show `today` for `x hours ago`, how can I do that?

**Comment by oferRounds** [comment]
@yas375 - thanks I missed your comment back then! Thank you!

**Comment by yas375** [comment]
@RishabhTayal currently it's not supported but the library. But you can just ask NSCalendar if a date is today and if so, then return localized `today`. Remember that you will need to localize this string yourself in case your app supports multiple languages. If `isDateInToday` returns false, then ask formatter.
