### ISSUE TITLE
Feature Request: Floor Numbering Formatter

### ISSUE THREAD

**Issue by colegleason** [mattt/FormatterKit#197]
I am trying to build an app that has internationalized floor numbers, and I was hoping to use the Ordinal Number formatter. Unfortunately, that didn't work as not all languages number floors using ordinal numbers, and some don't follow the same numbering scheme. I would love a formatter that returned the building floor specifier used in a specific language or area based on a the number of floors from the ground level.

For example, assuming the formatter assumed a US view, 1 would mean the floor at street level. Here is an example based on the input of the digit 3 and the locale:

  Country | String Returned
  ----------- | --------------------
  US | 3rd Floor
  UK | 2nd Floor
  China | 三樓

Note that there are both differences in numbering (US vs UK offset, for one) and also format (English uses ordinal numbers and Chinese does not). Another problem is that basement levels can have a different scheme than the upper levels.

Here is a Wikipedia article noting some of the differences: https://en.wikipedia.org/wiki/Storey#Numbering

**Comment by yas375** [comment]
I'm sorry, but I don't have plans in near future for implementing this. If more folks will express interest in this then might prioritize.
