### ISSUE TITLE
TTTTimeIntervalFormatter and "A week ago" rather than "1 week ago"

### ISSUE THREAD

**Issue by Ricardo1980** [mattt/FormatterKit#204]
Hello!

Is it possible to see strings like:

"A year ago" or "An hour" rather than "1 year ago" or "1 hour ago"?

If not possible, any recommendation about how I could modify the library to do that?

**Comment by yas375** [comment]
Currently this is not possible with the lib. I'm not sure if it worth to add this functionality to the library at this point.

> If not possible, any recommendation about how I could modify the library to do that?

You might want to use a fork of this lib with a modification. You will need to modify [this line](https://github.com/mattt/FormatterKit/blob/ca145baba604c3cdd09070970c0ec0e51ce4b98f/FormatterKit/TTTTimeIntervalFormatter.m#L168).
