### ISSUE TITLE
updating 2014 Obj-C with FormatterKit/TimeIntervalFormatter', '~> 1.6' pod

### ISSUE THREAD

**Issue by tysunmac** [mattt/FormatterKit#207]
Hi

FormatterKit is at 1.8 and my 2014 project is using 1.6 however it's named differently.
`pod 'FormatterKit/TimeIntervalFormatter'` Can I just change it to `pod FormatterKit`? Or have the methods and headers changed too? 

What do you recommend? Thanks

**Comment by yas375** [comment]
You should be still able to use `pod 'FormatterKit/TimeIntervalFormatter'` if you only want to add this formatter to your project. You can also use `pod 'FormatterKit'` to add all available formatters.

I can't answer the question about api difference from top of my head. I would suggest to try to upgrade and you will see if there are any breaking api changes.

You can also review the changes by comparing the tags: https://github.com/mattt/FormatterKit/compare/1.6.0...1.8.0
