### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by bejo** [mattt/FormatterKit#213]
@yas375 What's the current policy of creating new releases? I'm looking forward to see the recent changes in a new official version of the pod.

**Comment by yas375** [comment]
I don't have a strict opinion on this. Are there a lot of people who wants to see a release?

Also reminding that if you are using CocoaPods you can easily reference to any commit. For example current latest commit on `master`: `pod 'FormatterKit', :git => 'https://github.com/mattt/FormatterKit.git', :commit => '96401b2'`.

**Comment by bejo** [comment]
I want to see a release, let's see how many people will up vote this :)

At the moment I'm just referencing a commit in my Podfile. Using releases is a better solution for CocoaPods users since it (usually) guarantees that the pod is in a stable state.

**Comment by onomated** [comment]
+1

**Comment by grgcombs** [comment]
I'd at least like to see a release that gets rid of the deprecated address book stuff.  Is anyone else working on a pull request for that aspect?  If not, I can start working on one...

**Comment by richardbuckle** [comment]
+1

**Comment by mliberatore** [comment]
+1

**Comment by yas375** [comment]
Ok-ok :) I've asked Mattt to grant me permissions to submit new releases to CocoaPods trunk :)

**Comment by mliberatore** [comment]
> Ok-ok :) I've asked Mattt to grant me permissions to submit new releases to CocoaPods trunk :)

Thanks! :tada:

**Comment by yas375** [comment]
I have an access to submit a new release to cocoapods. I expect to do it in next couple days. I want to verify and fix if needed a few issues related to CocoaPods (#177, #182, #161, #158) before the release.

**Comment by yas375** [comment]
`1.8.1` is out!
