### ISSUE TITLE
Can't add FormatterKit pod to watchOS target

### ISSUE THREAD

**Issue by otaran** [mattt/FormatterKit#223]
```
$ cat Podfile
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
project 'XXX/XXX.xcodeproj'

target 'YYY' do
    platform :watchos, '2.0'
    pod 'FormatterKit/TimeIntervalFormatter', '= 1.8.1'
end

$ pod install
Analyzing dependencies
[!] The platform of the target `YYY` (watchOS 2.0) is not compatible with `FormatterKit/TimeIntervalFormatter (1.8.1)`, which does not support `watchos`.
```

**Comment by yas375** [comment]
No one has added watchOS support for this library yet. https://github.com/mattt/FormatterKit/blob/552f903e35a3758bd2666d4fe4a300590e6d426b/FormatterKit.podspec#L15-L16

Currently I have some other priorities, but you are more than welcome to do so. Here is what I'd like to see here:
1. update podscpec
2. add a target to FormatterKit.xcodeproj so Carthage users can use it as well.
3. Add "CocoaPods-watchOS" and "Carthage-watchOS" to IntegrationTests and modify `Rakefile` and `.travis.yml` to run them as part of integration tests.

**Comment by otaran** [comment]
`FormatterKit` used to work with `watchOS` before those `deployment_target` lines were added. I believe it is a regression introduced in `1.8.1`.

I can do 1) and 2), but 3) is not clear to me: watchOS targets don't support Unit Tests. I can copy project from `{Carthage,CocoaPods}-iOS` directories, but `run.sh` won't be usable. The best I could do is to verify that `xcodebuild ... build` successfully builds the app, i.e. it builds and links `FormatterKit` to `watchOS` app target.

Do you know what should I do with 3), @yas375 ?

**Comment by yas375** [comment]
Let's run `xcodebuild ... build` instead of `... test` 👍 
The main goal of these integration tests is to make sure the library can be integrated to an existing project using one of supported methods. And so if we update the podspec in future or do other changes we don't break it.

**Comment by yas375** [comment]
Thanks for the contribution!
