### ISSUE TITLE
when export/import .xittf for localization, there is a error

### ISSUE THREAD

**Issue by myzcid** [mattt/FormatterKit#231]
localization failed to read a strings file please check the system log for more details

Nov  7 10:38:59 MarkdeMacBook-Pro com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Nov  7 10:38:59 MarkdeMacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.IDECacheDeleteAppExtension.987): Path not allowed in target domain: type = pid, path = /Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/XPCServices/RootDebuggingXPCService.xpc error = 147: The specified service did not ship in the requestor's bundle, origin = /Applications/Xcode.app/Contents/PlugIns/IDECacheDeleteAppExtension.appex

OS:10.12.1
Xcode:8.1

**Comment by yas375** [comment]
@myzcid could you please provide repro steps? I'm not sure what `.xittf` is. Thanks.
