### ISSUE TITLE
Is it possible to achieve this: "3m ago"

### ISSUE THREAD

**Issue by warpling** [mattt/FormatterKit#236]
I made my own fork awhile back to do this since it seemed impossible at the time but thought it'd be worth asking! Making I'm not groking the powerful features of FormatterKit well enough!

**Comment by yas375** [comment]
You can do `3 min ago`:

```swift
let formatter = TTTTimeIntervalFormatter()
formatter.usesAbbreviatedCalendarUnits = true
formatter.string(forTimeInterval: -180) // "3 min ago"
```

**Comment by warpling** [comment]
Thanks Matt. Look like I'll stick with [my fork](https://github.com/warpling/FormatterKit) for now!
